language: node_js
node_js:
  - "stable"

cache:
  directories:
  - node_modules

script:
  - npm run website

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: styleguide
  keep-history: true
  on:
    branch: master